<?php

return [
    'divider_key' => '_divider_more',

    'default_order' => [
        'dashboard',
        'payments',
        'payments_needs_review',
        'businesses',
        'support',
        'virtual_cards',
        'businesses_kyc',
        'renters_kyc',
        'rentals',
        'whatsapp_wallet',
        'withdrawals',
        'overdraft',
        'peer_lending_offers',
        'peer_lending_loans',
        'external_apis',
        '_divider_more',
        'processed_emails',
        'transaction_logs',
        'audits',
        'match_attempts',
        'invoices',
        'email_accounts',
        'account_numbers',
        'bank_email_templates',
        'test_transaction',
        'renters',
        'tickets',
        'tickets_scanner',
        'charity',
        'memberships',
        'developer_program',
        'desktop_telemetry',
        'whitelisted_emails',
        'pages',
        'settings',
        'email_templates',
        'staff',
    ],
];
