<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Request SQL-Injection Guard
    |--------------------------------------------------------------------------
    |
    | Scans incoming request payloads for common SQL-injection signatures
    | before values reach query construction logic.
    |
    */
    'sql_injection_guard' => [
        'enabled' => env('SQL_INJECTION_GUARD_ENABLED', true),

        'patterns' => [
            "/(?:'|\\\"|`)?\\s*(?:or|and)\\s+\\d+\\s*=\\s*\\d+/i",
            "/(?:union\\s+all\\s+select|union\\s+select)/i",
            "/(?:information_schema|mysql\\.user|pg_catalog)/i",
            "/(?:sleep\\s*\\(|benchmark\\s*\\(|pg_sleep\\s*\\()/i",
            "/(?:\\b(?:drop|truncate|alter)\\b\\s+\\b(?:database|schema|table)\\b)/i",
            "/(?:--\\s+|#\\s+|\\/\\*)/i",
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Outgoing SQL Query Firewall
    |--------------------------------------------------------------------------
    |
    | Inspects SQL text generated by the app at runtime. This blocks highly
    | destructive or exfiltration-oriented statements in web traffic while
    | still allowing normal app queries.
    |
    */
    'query_firewall' => [
        'enabled' => env('DB_QUERY_FIREWALL_ENABLED', true),
        'block_in_console' => env('DB_QUERY_FIREWALL_BLOCK_IN_CONSOLE', false),

        'patterns' => [
            "/\\bdrop\\s+(?:database|schema|table)\\b/i",
            "/\\btruncate\\s+table\\b/i",
            "/\\balter\\s+(?:database|schema)\\b/i",
            "/\\b(?:create|alter|drop)\\s+user\\b/i",
            "/\\b(?:grant|revoke)\\b/i",
            "/\\binto\\s+(?:outfile|dumpfile)\\b/i",
            "/\\bload\\s+data\\s+(?:local\\s+)?infile\\b/i",
            "/\\bload_file\\s*\\(/i",
            "/\\bmysql\\.(?:user|db|tables_priv|columns_priv)\\b/i",
            "/;\\s*(?:drop|truncate|alter|create|grant|revoke|delete|update|insert|select)\\b/i",
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Public registration abuse guard (business signup, developer program, etc.)
    |--------------------------------------------------------------------------
    */
    'registration_abuse_guard' => [
        'enabled' => env('REGISTRATION_ABUSE_GUARD_ENABLED', true),
        'block_tor_exits' => env('REGISTRATION_ABUSE_BLOCK_TOR', true),
        'require_website_dns' => env('REGISTRATION_ABUSE_REQUIRE_WEBSITE_DNS', true),
        'rdns_cache_seconds' => (int) env('REGISTRATION_ABUSE_RDNS_CACHE_SECONDS', 3600),
        'dns_cache_seconds' => (int) env('REGISTRATION_ABUSE_DNS_CACHE_SECONDS', 3600),
        'tor_rdns_needles' => [
            'tor-exit',
            '.relayon.org',
            'relayon.org',
        ],
    ],
];
