<?php

return [
    'site_name' => 'CheckoutPay',
    'site_name_consumer' => 'CheckoutNow',
    'default_title' => 'CheckoutPay — Affordable & Reliable Payment Gateway in Nigeria',
    'default_description' => 'CheckoutPay is a low-cost, reliable payment gateway for Nigerian businesses — plus WhatsApp Wallet to send money to anyone on WhatsApp or to any bank. Bank transfer matching, virtual accounts, WooCommerce plugin, and transparent fees.',
    'default_keywords' => 'payment gateway Nigeria, cheapest payment gateway Nigeria, reliable payment gateway, bank transfer payments Nigeria, WooCommerce payment Nigeria, virtual account checkout, WordPress payment plugin Nigeria, payment gateway API Nigeria, developer payment gateway program Nigeria, CheckoutPay, check-outpay',
    'locale' => 'en_NG',
    'twitter_handle' => '@CheckoutPayNG',
    'google_site_verification' => 'gDWop-gnIIBUlNGs0xdQRs47Rwi5wIm3Tg-eQ9kissk',
    'og_image' => '/checkout-logo.png',
    'organization' => [
        'legal_name' => 'CheckoutPay',
        'url' => null,
        'logo' => '/checkout-logo.png',
        'area_served' => 'Nigeria',
        'price_range' => '₦',
    ],
    /**
     * CMS page slugs that also have a top-level route (e.g. /privacy-policy).
     * /page/{slug} requests 301 to the preferred URL; sitemap uses the same path.
     */
    'dedicated_page_slugs' => [
        'privacy-policy',
        'terms-and-conditions',
        'security',
        'fraud-awareness',
        'esg-policy',
    ],
    'sitemap_exclude_page_slugs' => [
        'home',
        'pricing',
        'faqs',
        'blog',
    ],
    'sitemap_paths' => [
        '/',
        '/pricing',
        '/products',
        '/products/invoices',
        '/products/memberships',
        '/products/memberships-info',
        '/products/rentals-info',
        '/products/tickets-info',
        '/whatsapp-wallet',
        '/wordpress-plugin',
        '/developers',
        '/developers/program',
        '/developers/program/apply',
        '/api-docs',
        '/collections',
        '/payout',
        '/checkout-demo',
        '/about-us',
        '/support',
        '/contact',
        '/faqs',
        '/status',
        '/security',
        '/fraud-awareness',
        '/esg-policy',
        '/resources',
        '/blog',
        '/careers',
        '/marketplace',
        '/business-loans',
        '/charity',
        '/tickets',
        '/privacy-policy',
        '/terms-and-conditions',
        '/site-map',
    ],
    'sitemap_priority' => [
        '/' => '1.0',
        '/pricing' => '0.9',
        '/wordpress-plugin' => '0.9',
        '/api-docs' => '0.9',
        '/developers/program' => '0.9',
        '/whatsapp-wallet' => '0.9',
        '/faqs' => '0.9',
        '/developers' => '0.85',
        '/products' => '0.85',
        '/support' => '0.8',
        '/contact' => '0.8',
        '/privacy-policy' => '0.5',
        '/terms-and-conditions' => '0.5',
    ],
];
